Sprucing up error messaging a bit. Indenting errors for each file, adding the puppet-lint errors and erb errors to the output

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -57,17 +57,20 @@ do
                 # puppet syntax check
                 puppet parser validate $TMPFILE > /dev/null 2>&1
                 if [ $? -ne 0 ] ; then
-                    echo "Puppet syntax error in $file" >&2
+                    echo "Puppet syntax error in $file:" >&2
                     # Provide some useful output about what you did wrong
-                    OUTPUT=`puppet parser validate --color false $TMPFILE 2>/dev/null`
-                    echo $OUTPUT |sed "s/\/tmp\/.*:\([0-9]\+\).*/line\ \1/" >&2
+                    OUTPUT=`puppet parser validate --color false $TMPFILE 2>&1 | grep -v 'puppet help parser validate'`
+                    echo "$OUTPUT" |sed "s/\/tmp\/.*:\([0-9]\+\).*/line\ \1/" | sed 's/^/  /' >&2
                     STATUS=2
                 fi
 
                 # puppet lint check
                 puppet-lint $LINTFLAGS $TMPFILE > /dev/null 2>&1
                 if [ $? -ne 0 ] ; then
-                    echo "Puppet lint error in $file" >&2
+                    # Provide some useful output about what you did wrong
+                    echo "Puppet lint error in $file:" >&2
+                    OUTPUT=`puppet-lint $LINTFLAGS $TMPFILE 2>/dev/null`
+                    echo "$OUTPUT" | sed 's/^/  /' >&2
                     STATUS=2
                 fi
             ;;
@@ -77,7 +80,9 @@ do
                 # but it should catch gross mistakes
                 erb -P -x -T - "$TMPFILE" | ruby -c > /dev/null 2>&1
                 if [ $? -ne 0 ] ; then
-                    echo "ERB syntax error in $file" >&2
+                    echo "ERB syntax error in $file:" >&2
+                    OUTPUT=`erb -P -x -T - "$TMPFILE" | ruby -c 2>&1`
+                    echo "$OUTPUT" | sed 's/^/  /' >&2
                     STATUS=2
                 fi
             ;;
